--Snowflake SQL to create the Adult 4 table
CREATE TABLE DEV__MODELLING.CANCER__SURVIVAL.ADULT_4 (
    "AREA_TYPE" VARCHAR,
    "AREA_CODE" VARCHAR,
    "AREA_NAME" VARCHAR,
    "IS_AREA_CORE" BOOLEAN,
    "CANCER_SITE" VARCHAR,
    "GENDER" VARCHAR,
    "STANDARDISATION_TYPE" VARCHAR,
    "STANDARDISATION_TYPE_SUBCATEGORY" VARCHAR,
    "YEARS_SINCE_DIAGNOSIS" NUMBER,
    "PATIENT_NUMBERS" NUMBER,
    "SURVIVAL_METRIC" VARCHAR,
    "SURVIVAL_PERCENT" FLOAT,
    "DATE_DIAGNOSIS_WINDOW" VARCHAR,
    "DATE_SNAPSHOT" VARCHAR,
    "_TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)