--Snowflake SQL to create the Index table
CREATE TABLE DEV__MODELLING.CANCER__SURVIVAL.INDEX(
    "AREA_CODE" VARCHAR,
    "AREA_NAME" VARCHAR,
    "CANCER_SITE" VARCHAR,
    "GENDER" VARCHAR,
    "AGE_AT_DIAGNOSIS" VARCHAR,
    "STANDARDISATION_TYPE" VARCHAR,
    "YEAR_OF_DIAGNOSIS" NUMBER,
    "YEARS_SINCE_DIAGNOSIS" NUMBER,
    "PATIENT_NUMBERS" NUMBER,
    "SURVIVAL_PERCENT" FLOAT,
    "LOWER_CI" FLOAT,
    "UPPER_CI" FLOAT,
    "PRECISION" FLOAT,
    "STANDARD_ERROR" FLOAT,
    "IS_DATA_SUBTITUTED" BOOLEAN,
    "_TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)