create or replace view REPORTING.CANCER__SURVIVAL.CANCER_ALLIANCE_COMPARISON(
	AREA_TYPE,
	AREA_CODE,
	AREA_NAME,
	IS_AREA_CORE,
	CANCER_SITE,
	GENDER,
	STANDARDISATION_TYPE,
	STANDARDISATION_TYPE_SUBCATEGORY,
	YEARS_SINCE_DIAGNOSIS,
	PATIENT_NUMBERS,
	SURVIVAL_METRIC,
	SURVIVAL_PERCENT,
	DATE_DIAGNOSIS_WINDOW,
	DATE_SNAPSHOT,
	JOIN_KEY,
	SORT_GENDER
) COMMENT='Reporting View for Survival Dashboard'
AS

--Script to pull in the data for core areas in the adult4 data
SELECT 
    * EXCLUDE _TIMESTAMP, 
	CONCAT(CANCER_SITE, GENDER, YEARS_SINCE_DIAGNOSIS, DATE_DIAGNOSIS_WINDOW) AS JOIN_KEY,
    CASE GENDER
        WHEN 'Persons' THEN 1
        ELSE 2
    END AS SORT_GENDER
FROM MODELLING.CANCER__SURVIVAL.ADULT_4
WHERE AREA_TYPE = 'Cancer Alliance'
AND STANDARDISATION_TYPE = 'Age-standardised' 
AND SURVIVAL_METRIC = 'Net Survival';

CREATE OR REPLACE VIEW PUBLISHED_REPORTING__SECONDARY_USE.CANCER__SURVIVAL.CANCER_ALLIANCE_COMPARISON
COMMENT="Published View for Survival Dashboard"
AS

SELECT
AREA_TYPE AS "Area_Type", 
AREA_CODE AS "Area_Code", 
AREA_NAME AS "Area_Name", 
IS_AREA_CORE AS "Area_Core", 
CANCER_SITE AS "Cancer_Site", 
GENDER AS "Gender", 
STANDARDISATION_TYPE AS "Standardisation_Type", 
STANDARDISATION_TYPE_SUBCATEGORY AS "Standardisation_Subcategory", 
YEARS_SINCE_DIAGNOSIS AS "Years_Since_Diagnosis", 
PATIENT_NUMBERS AS "Patient_Numbers", 
SURVIVAL_METRIC AS "Survival_Metric", 
SURVIVAL_PERCENT AS "Survival_Per", 
DATE_DIAGNOSIS_WINDOW AS "Date_Diagnosis_Window", 
DATE_SNAPSHOT AS "Date_Snapshot", 
JOIN_KEY,
SORT_GENDER AS "Sort_Gender"

FROM REPORTING.CANCER__SURVIVAL.CANCER_ALLIANCE_COMPARISON;