create or replace view DEV__REPORTING.CANCER__SURVIVAL.INDEX_BEST_CA(
	AREA_CODE,
	AREA_NAME,
    IS_AREA_CORE,
	CANCER_SITE,
	GENDER,
	AGE_AT_DIAGNOSIS,
	STANDARDISATION_TYPE,
	YEAR_OF_DIAGNOSIS,
	YEARS_SINCE_DIAGNOSIS,
	PATIENT_NUMBERS,
	SURVIVAL_PERCENT,
	LOWER_CI,
	UPPER_CI,
	PRECISION,
	STANDARD_ERROR,
	IS_DATA_SUBTITUTED
    
) COMMENT='Reporting View for Survival Dashboard'
 as

SELECT 
    'X' AS AREA_CODE,
    'Best Non-NCL Cancer Alliance' AS AREA_NAME,
    IS_AREA_CORE,
    CANCER_SITE,
    GENDER,
    AGE_AT_DIAGNOSIS,
    STANDARDISATION_TYPE,
    YEAR_OF_DIAGNOSIS,
    YEARS_SINCE_DIAGNOSIS,
    NULL AS PATIENT_NUMBERS,
	MAX(SURVIVAL_PERCENT),
	NULL AS LOWER_CI,
	NULL AS UPPER_CI,
	NULL AS PRECISION,
	NULL AS STANDARD_ERROR,
	NULL AS IS_DATA_SUBTITUTED
    
FROM DEV__MODELLING.CANCER__SURVIVAL.INDEX
WHERE IS_AREA_CORE = FALSE
GROUP BY ALL;