create or replace view DEV__REPORTING.CANCER__SURVIVAL.INDEX(
	AREA_CODE,
	AREA_NAME,
    IS_AREA_CORE,
	CANCER_SITE,
	GENDER,
	AGE_AT_DIAGNOSIS,
	STANDARDISATION_TYPE,
	YEAR_OF_DIAGNOSIS,
	YEARS_SINCE_DIAGNOSIS,
	PATIENT_NUMBERS,
	SURVIVAL_PERCENT,
	LOWER_CI,
	UPPER_CI,
	PRECISION,
	STANDARD_ERROR,
	IS_DATA_SUBTITUTED,
	SORT_SITE,
	SORT_GENDER,
	SORT_AGE
) COMMENT='Reporting View for Survival Dashboard'
 as

SELECT 
    *,
    CASE CANCER_SITE
        WHEN 'Overall' THEN 1
        ELSE 2
    END AS SORT_SITE,
    
    CASE GENDER
        WHEN 'Persons' THEN 1
        ELSE 2
    END AS SORT_GENDER,
    
    CASE AGE_AT_DIAGNOSIS
        WHEN 'All ages' THEN 1
        ELSE 2
    END AS SORT_AGE
    
FROM (
    SELECT * EXCLUDE _TIMESTAMP 
    FROM DEV__MODELLING.CANCER__SURVIVAL.INDEX
    WHERE IS_AREA_CORE = TRUE
    
    UNION ALL
    SELECT * 
    FROM DEV__REPORTING.CANCER__SURVIVAL.INDEX_BEST_CA
);