CREATE OR REPLACE VIEW DEV__REPORTING.CANCER__SURVIVAL.BENCHMARKING_RANK 
COMMENT="Reporting View for Survival Dashboard"
AS

WITH CA_RANK (AREA_CODE, JOIN_KEY, SURVIVAL_PERCENT, RANK_CA) AS (
    --Rank each CA for each JOIN KEY combination
    SELECT AREA_CODE,
    	CONCAT(CANCER_SITE, GENDER, YEARS_SINCE_DIAGNOSIS, DATE_DIAGNOSIS_WINDOW) AS JOIN_KEY,
        SURVIVAL_PERCENT,
        RANK() OVER (PARTITION BY JOIN_KEY ORDER BY SURVIVAL_PERCENT DESC) AS RANK_CA
    FROM DEV__MODELLING.CANCER__SURVIVAL.ADULT_4
    WHERE (STANDARDISATION_TYPE = 'Age-standardised' 
        AND SURVIVAL_METRIC = 'Net Survival' 
        AND AREA_TYPE = 'Cancer Alliance'
    )
    AND SURVIVAL_PERCENT IS NOT NULL
),
CA_BASE AS (
    --Get the denominator for each JOIN KEY (CA's with non-null data)
    SELECT
        CANCER_SITE,
        CONCAT(CANCER_SITE, GENDER, YEARS_SINCE_DIAGNOSIS, DATE_DIAGNOSIS_WINDOW) AS JOIN_KEY,
        COUNT(1) AS RANK_BASE
    FROM DEV__MODELLING.CANCER__SURVIVAL.ADULT_4
    WHERE (STANDARDISATION_TYPE = 'Age-standardised' 
        AND SURVIVAL_METRIC = 'Net Survival' 
        AND AREA_TYPE = 'Cancer Alliance'
    )
    AND SURVIVAL_PERCENT IS NOT NULL
    GROUP BY CANCER_SITE, GENDER, YEARS_SINCE_DIAGNOSIS, DATE_DIAGNOSIS_WINDOW
)
SELECT 
    CA_BASE.JOIN_KEY,
    CA_BASE.CANCER_SITE,
    CA_RANK.SURVIVAL_PERCENT,
    CA_RANK.RANK_CA,
    RANK_BASE,
    CASE
        WHEN RANK_CA IS NULL THEN NULL
        WHEN RANK_BASE < 4 THEN '-'
        WHEN RANK_CA / RANK_BASE < 0.25 THEN '1st'
        WHEN RANK_CA / RANK_BASE < 0.5 THEN '2nd'
        WHEN RANK_CA / RANK_BASE < 0.75 THEN '3rd'
        ELSE '4th'
    END AS NCL_QUARTILE
    
FROM CA_BASE

LEFT JOIN CA_RANK 
ON CA_RANK.JOIN_KEY = CA_BASE.JOIN_KEY
AND AREA_CODE = 'E56000027';

CREATE OR REPLACE VIEW DEV__PUBLISHED_REPORTING__SECONDARY_USE.CANCER__SURVIVAL.BENCHMARKING_RANK 
COMMENT="Published View for Survival Dashboard"
AS

SELECT
JOIN_KEY, 
CANCER_SITE AS "Cancer_Site", 
SURVIVAL_PERCENT AS "Survival_Per", 
RANK_CA AS "Rank_CA", 
RANK_BASE AS "Rank_Denominator", 
NCL_QUARTILE AS "Quartile"

FROM DEV__REPORTING.CANCER__SURVIVAL.BENCHMARKING_RANK 