CREATE OR REPLACE VIEW DEV__REPORTING.CANCER__SURVIVAL.BENCHMARKING_STANDARDS 
COMMENT="Reporting View for Survival Dashboard"
AS

WITH A4_BASE (AREA_CODE, AREA_NAME, AREA_TYPE, JOIN_KEY, CANCER_SITE, GENDER, YEARS_SINCE_DIAGNOSIS, DATE_DIAGNOSIS_WINDOW, SURVIVAL_PERCENT) AS (
    SELECT 
        AREA_CODE, AREA_NAME, AREA_TYPE,
        CONCAT(CANCER_SITE, GENDER, YEARS_SINCE_DIAGNOSIS, DATE_DIAGNOSIS_WINDOW) AS JOIN_KEY, 
        CANCER_SITE, GENDER, YEARS_SINCE_DIAGNOSIS, DATE_DIAGNOSIS_WINDOW, SURVIVAL_PERCENT
    FROM DEV__MODELLING.CANCER__SURVIVAL.ADULT_4
    WHERE 
        STANDARDISATION_TYPE = 'Age-standardised' 
        AND SURVIVAL_METRIC = 'Net Survival'
)

SELECT 
    JOIN_KEY,
    "'England'" AS ENGLAND,
    "'London'" AS LONDON,
    "'Best'" AS BEST,
    "'Worst'" AS WORST,
    "'Q1'" AS Q1,
    "'Q2'" AS Q2,
    "'Q3'" AS Q3
FROM (     
    --Set up Benchmark Standards
    ----England
    SELECT 
        JOIN_KEY,
        AREA_NAME AS STANDARD,
        SURVIVAL_PERCENT
    FROM A4_BASE
    WHERE AREA_CODE = 'E92000001'
    
    UNION ALL
    ----London
    SELECT 
        JOIN_KEY,
        AREA_NAME AS STANDARD,
        SURVIVAL_PERCENT
    FROM A4_BASE
    WHERE AREA_CODE = 'E40000003'
    
    UNION ALL
    ----Best
    SELECT 
        JOIN_KEY,
        'Best' AS STANDARD,
        MAX(SURVIVAL_PERCENT)
    FROM A4_BASE
    WHERE AREA_TYPE = 'Cancer Alliance'
    GROUP BY JOIN_KEY
    
    UNION ALL
    ----Worst
    SELECT 
        JOIN_KEY,
        'Worst' AS STANDARD,
        MIN(SURVIVAL_PERCENT)
    FROM A4_BASE
    WHERE AREA_TYPE = 'Cancer Alliance'
    GROUP BY JOIN_KEY
    
    UNION ALL
    ----Q1
    SELECT 
        JOIN_KEY,
        'Q1' AS STANDARD,
        PERCENTILE_DISC(0.25) WITHIN GROUP (ORDER BY SURVIVAL_PERCENT) AS percentile_value
    FROM A4_BASE
    WHERE AREA_TYPE = 'Cancer Alliance'
    GROUP BY JOIN_KEY
    
    UNION ALL
    ----Q2
    SELECT 
        JOIN_KEY,
        'Q2' AS STANDARD,
        PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY SURVIVAL_PERCENT) AS percentile_value
    FROM A4_BASE
    WHERE AREA_TYPE = 'Cancer Alliance'
    GROUP BY JOIN_KEY
    
    UNION ALL
    ----Q3
    SELECT 
        JOIN_KEY,
        'Q3' AS STANDARD,
        PERCENTILE_DISC(0.75) WITHIN GROUP (ORDER BY SURVIVAL_PERCENT) AS percentile_value
    FROM A4_BASE
    WHERE AREA_TYPE = 'Cancer Alliance'
    GROUP BY JOIN_KEY
) std
PIVOT (
    SUM(SURVIVAL_PERCENT) 
    FOR STANDARD IN ('England', 'London', 'Best', 'Worst', 'Q1', 'Q2', 'Q3')
);

CREATE OR REPLACE VIEW DEV__PUBLISHED_REPORTING__SECONDARY_USE.CANCER__SURVIVAL.BENCHMARKING_STANDARDS 
COMMENT="Published View for Survival Dashboard"
AS

SELECT
JOIN_KEY, 
ENGLAND AS "England", 
LONDON AS "London", 
BEST AS "Best", 
WORST AS "Worst", 
Q1, 
Q2, 
Q3

FROM DEV__REPORTING.CANCER__SURVIVAL.BENCHMARKING_STANDARDS 